#This is the check and streamlit auto deploys any push to main
#This will alert of install/syntax errors before deploying to app

name: Streamlit CI #Workflow Name

on: #Run everytime there is a push to main
  push:
    branches:
      - main  

jobs: #Run on ubuntu
  test-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo #checkout repo so that it can be run
        uses: actions/checkout@v3

      - name: Set up Python #install python for running
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies #install packages from "requirements.txt" note: if this fails WebApp would fail
        run: |
          python -m pip install --upgrade pip
          pip install -r Web_App/requirements.txt
          pip install Pillow ultralytics  # Required for integration tests

      - name: Lint #Check for errors
        run: |
          pip install flake8 
          flake8 Web_App/ --ignore=E501,E402 
        #ignore long lines and imports not at top because we have to preempt imports to fix runtime errors on cloud                  

      - name: Integration Testing
        run: |
          # Run the integration test script
          python Testing_Files/integration_test.py
          
          # Display the results
          cat test_results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: test_results.txt

      # Optional: Run tests if you have a test suite
      # - name: Run tests
      #   run: pytest


